[package]
name = "better-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "better_core"
path = "src/lib.rs"

[[bin]]
name = "better-core"
path = "src/main.rs"

[dependencies]
ureq = { version = "2", features = ["tls"] }
sha2 = "0.10"
flate2 = "1"
tar = "0.4"
rayon = "1"
base64 = "0.22"
