[package]
name = "better-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
better-core = { path = "../better-core" }
napi = { version = "2", features = ["napi6"] }
napi-derive = "2"
rayon = "1"

[build-dependencies]
napi-build = "2"
